// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelManagement.API.Data;

#nullable disable

namespace TravelManagement.API.Data.Migrations
{
    [DbContext(typeof(TravelDbContext))]
    [Migration("20260511125739_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TravelManagement.API.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Adults")
                        .HasColumnType("int");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("BookedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("BookingReference")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Children")
                        .HasColumnType("int");

                    b.Property<string>("CustomItinerary")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SpecialRequests")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TourPackageId")
                        .HasColumnType("int");

                    b.Property<int?>("TourScheduleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TripEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TripStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookingReference")
                        .IsUnique();

                    b.HasIndex("CustomerId");

                    b.HasIndex("TourPackageId");

                    b.HasIndex("TourScheduleId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("TravelManagement.API.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("City")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Country")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdProofNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdProofType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("State")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "12 MG Road",
                            City = "Bengaluru",
                            Country = "India",
                            PostalCode = "560001",
                            State = "Karnataka",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("TravelManagement.API.Models.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LicenseExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("LicenseNumber")
                        .IsUnique();

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExperienceYears = 8,
                            FullName = "Ravi Kumar",
                            IsAvailable = true,
                            LicenseExpiry = new DateTime(2028, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LicenseNumber = "KA0120240001",
                            Phone = "+919000000001"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExperienceYears = 12,
                            FullName = "Suresh Patel",
                            IsAvailable = true,
                            LicenseExpiry = new DateTime(2027, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LicenseNumber = "KA0120240002",
                            Phone = "+919000000002"
                        });
                });

            modelBuilder.Entity("TravelManagement.API.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PaidBy")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("TourPackageId")
                        .HasColumnType("int");

                    b.Property<string>("Vendor")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("TourPackageId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("TravelManagement.API.Models.Facility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Facilities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 300m,
                            IsActive = true,
                            Name = "Breakfast",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Cost = 500m,
                            IsActive = true,
                            Name = "Lunch",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Cost = 600m,
                            IsActive = true,
                            Name = "Dinner",
                            Type = 2
                        },
                        new
                        {
                            Id = 4,
                            Cost = 2500m,
                            IsActive = true,
                            Name = "3-Star Hotel Stay",
                            Type = 3
                        },
                        new
                        {
                            Id = 5,
                            Cost = 1500m,
                            IsActive = true,
                            Name = "AC Transportation",
                            Type = 4
                        },
                        new
                        {
                            Id = 6,
                            Cost = 1200m,
                            IsActive = true,
                            Name = "Local Guide",
                            Type = 5
                        });
                });

            modelBuilder.Entity("TravelManagement.API.Models.Itinerary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Accommodation")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Activities")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("DayNumber")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Location")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Meals")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TourPackageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TourPackageId");

                    b.ToTable("Itineraries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Accommodation = "3* Hotel, Delhi",
                            Activities = "Red Fort, India Gate, Qutub Minar",
                            DayNumber = 1,
                            Description = "Arrival, city tour of Old & New Delhi.",
                            Location = "Delhi",
                            Meals = "Breakfast",
                            Title = "Arrive Delhi",
                            TourPackageId = 1
                        },
                        new
                        {
                            Id = 2,
                            Accommodation = "3* Hotel, Jaipur",
                            Activities = "Taj Mahal, Agra Fort",
                            DayNumber = 2,
                            Description = "Visit Taj Mahal & Agra Fort, drive to Jaipur.",
                            Location = "Agra/Jaipur",
                            Meals = "Breakfast",
                            Title = "Delhi-Agra-Jaipur",
                            TourPackageId = 1
                        },
                        new
                        {
                            Id = 3,
                            Accommodation = "-",
                            Activities = "Amber Fort, Hawa Mahal",
                            DayNumber = 3,
                            Description = "Amber Fort, City Palace, departure.",
                            Location = "Jaipur",
                            Meals = "Breakfast",
                            Title = "Jaipur city tour & departure",
                            TourPackageId = 1
                        });
                });

            modelBuilder.Entity("TravelManagement.API.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("TravelManagement.API.Models.PackageFacility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<bool>("Included")
                        .HasColumnType("bit");

                    b.Property<int>("TourPackageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.HasIndex("TourPackageId");

                    b.ToTable("PackageFacilities");
                });

            modelBuilder.Entity("TravelManagement.API.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GatewayResponse")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GatewayTransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("InitiatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Method")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionReference")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("TransactionReference")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("TravelManagement.API.Models.Refund", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("ApprovedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("RequestedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("Refunds");
                });

            modelBuilder.Entity("TravelManagement.API.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasFilter("[BookingId] IS NOT NULL");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TourId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("TravelManagement.API.Models.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Department")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Designation")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StaffMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "Operations",
                            Designation = "Tour Coordinator",
                            JoinedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("TravelManagement.API.Models.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Destination")
                        .HasColumnType("int");

                    b.Property<string>("Highlights")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Region")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tours");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Explore the iconic Golden Triangle covering Delhi, Agra and Jaipur.",
                            Destination = 0,
                            Highlights = "Taj Mahal, Amber Fort, Qutub Minar",
                            ImageUrl = "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800",
                            IsActive = true,
                            Name = "Golden Triangle Discovery",
                            Region = "Delhi-Agra-Jaipur"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A serene cruise through Kerala's famous backwaters and lush hills.",
                            Destination = 0,
                            Highlights = "Alleppey houseboats, Munnar tea gardens, Kochi",
                            ImageUrl = "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800",
                            IsActive = true,
                            Name = "Kerala Backwaters Bliss",
                            Region = "Kerala"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Discover the kingdom of happiness with monasteries, dzongs and Himalayan views.",
                            Destination = 1,
                            Highlights = "Tiger's Nest, Punakha Dzong, Dochula Pass",
                            ImageUrl = "https://images.unsplash.com/photo-1580651315530-69c8e0903883?w=800",
                            IsActive = true,
                            Name = "Bhutan Cultural Trail",
                            Region = "Paro-Thimphu-Punakha"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Adventure through temples, lakes and Annapurna foothills.",
                            Destination = 2,
                            Highlights = "Pashupatinath, Phewa Lake, Sarangkot sunrise",
                            ImageUrl = "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800",
                            IsActive = true,
                            Name = "Nepal Himalayan Escape",
                            Region = "Kathmandu-Pokhara"
                        });
                });

            modelBuilder.Entity("TravelManagement.API.Models.TourPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal?>("ChildPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<int>("DurationNights")
                        .HasColumnType("int");

                    b.Property<string>("Exclusions")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Inclusions")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCustomizable")
                        .HasColumnType("bit");

                    b.Property<int>("MaxPersons")
                        .HasColumnType("int");

                    b.Property<int>("MinPersons")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("PricePerPerson")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TourId");

                    b.ToTable("TourPackages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChildPrice = 9999m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Quick 3-day getaway covering all highlights.",
                            DurationDays = 3,
                            DurationNights = 2,
                            Exclusions = "Flights, personal expenses",
                            Inclusions = "Hotel, breakfast, transport, guide",
                            IsActive = true,
                            IsCustomizable = true,
                            MaxPersons = 12,
                            MinPersons = 2,
                            Name = "Golden Triangle 3D/2N",
                            PricePerPerson = 14999m,
                            TourId = 1
                        },
                        new
                        {
                            Id = 2,
                            ChildPrice = 16999m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Extended deluxe experience with premium hotels.",
                            DurationDays = 5,
                            DurationNights = 4,
                            Exclusions = "Flights, tips",
                            Inclusions = "4* hotel, all meals, AC transport, guide",
                            IsActive = true,
                            IsCustomizable = true,
                            MaxPersons = 12,
                            MinPersons = 2,
                            Name = "Golden Triangle 5D/4N Deluxe",
                            PricePerPerson = 24999m,
                            TourId = 1
                        },
                        new
                        {
                            Id = 3,
                            ChildPrice = 14999m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Munnar, Thekkady, Alleppey and Kochi.",
                            DurationDays = 5,
                            DurationNights = 4,
                            Exclusions = "Lunch, personal expenses",
                            Inclusions = "Houseboat, hotel, breakfast & dinner",
                            IsActive = true,
                            IsCustomizable = true,
                            MaxPersons = 10,
                            MinPersons = 2,
                            Name = "Kerala 5D/4N Classic",
                            PricePerPerson = 22999m,
                            TourId = 2
                        },
                        new
                        {
                            Id = 4,
                            ChildPrice = 24999m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Comprehensive Bhutan cultural circuit.",
                            DurationDays = 6,
                            DurationNights = 5,
                            Exclusions = "Air tickets, personal expenses",
                            Inclusions = "Hotel, all meals, Bhutan visa, transport",
                            IsActive = true,
                            IsCustomizable = false,
                            MaxPersons = 10,
                            MinPersons = 2,
                            Name = "Bhutan 6D/5N Discovery",
                            PricePerPerson = 39999m,
                            TourId = 3
                        },
                        new
                        {
                            Id = 5,
                            ChildPrice = 11999m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kathmandu and Pokhara highlights.",
                            DurationDays = 4,
                            DurationNights = 3,
                            Exclusions = "Flights, lunch & dinner",
                            Inclusions = "Hotel, breakfast, transport, guide",
                            IsActive = true,
                            IsCustomizable = true,
                            MaxPersons = 12,
                            MinPersons = 2,
                            Name = "Nepal 4D/3N Highlights",
                            PricePerPerson = 18999m,
                            TourId = 4
                        });
                });

            modelBuilder.Entity("TravelManagement.API.Models.TourSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<int>("BookedSeats")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.Property<int>("TourPackageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TourId");

                    b.HasIndex("TourPackageId");

                    b.ToTable("TourSchedules");
                });

            modelBuilder.Entity("TravelManagement.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@travel.local",
                            FullName = "Administrator",
                            IsActive = true,
                            PasswordHash = "$2a$11$/s57prvPkHnOidcAK0ZNN.FFtewl81vKLlBf4tV1GeJK2zLzbYQBi",
                            Phone = "+910000000001",
                            Role = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "staff@travel.local",
                            FullName = "Staff One",
                            IsActive = true,
                            PasswordHash = "$2a$11$7OWJaNRtLB9aREI1T7saXeeFR7GEhUbPZz6XAW4NDrQBgLXOPYKn6",
                            Phone = "+910000000002",
                            Role = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "customer@travel.local",
                            FullName = "Demo Customer",
                            IsActive = true,
                            PasswordHash = "$2a$11$ZyotDVLFjnsuXKduYn2wjeujOZJFLBzGs9CTTXbZNxdu9sGMBOFDm",
                            Phone = "+910000000003",
                            Role = 0
                        });
                });

            modelBuilder.Entity("TravelManagement.API.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<decimal?>("CostPerDay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Make")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Model")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique();

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 6,
                            CostPerDay = 3500m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Make = "Toyota",
                            Model = "Innova Crysta",
                            Name = "Toyota Innova",
                            RegistrationNumber = "KA01AB1234",
                            Type = 0,
                            Year = 2022
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 17,
                            CostPerDay = 6500m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Make = "Force",
                            Model = "Traveller",
                            Name = "Force Traveller 17",
                            RegistrationNumber = "KA01CD5678",
                            Type = 2,
                            Year = 2021
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 45,
                            CostPerDay = 12000m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Make = "Volvo",
                            Model = "9400",
                            Name = "Volvo 45-seater",
                            RegistrationNumber = "KA01EF9012",
                            Type = 3,
                            Year = 2020
                        });
                });

            modelBuilder.Entity("TravelManagement.API.Models.VehicleAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("DriverId");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleAllocations");
                });

            modelBuilder.Entity("TravelManagement.API.Models.Booking", b =>
                {
                    b.HasOne("TravelManagement.API.Models.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravelManagement.API.Models.TourPackage", "TourPackage")
                        .WithMany("Bookings")
                        .HasForeignKey("TourPackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravelManagement.API.Models.TourSchedule", "TourSchedule")
                        .WithMany("Bookings")
                        .HasForeignKey("TourScheduleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");

                    b.Navigation("TourPackage");

                    b.Navigation("TourSchedule");
                });

            modelBuilder.Entity("TravelManagement.API.Models.Customer", b =>
                {
                    b.HasOne("TravelManagement.API.Models.User", "User")
                        .WithOne("Customer")
                        .HasForeignKey("TravelManagement.API.Models.Customer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelManagement.API.Models.Expense", b =>
                {
                    b.HasOne("TravelManagement.API.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TravelManagement.API.Models.TourPackage", "TourPackage")
                        .WithMany()
                        .HasForeignKey("TourPackageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Booking");

                    b.Navigation("TourPackage");
                });

            modelBuilder.Entity("TravelManagement.API.Models.Itinerary", b =>
                {
                    b.HasOne("TravelManagement.API.Models.TourPackage", "TourPackage")
                        .WithMany("Itineraries")
                        .HasForeignKey("TourPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TourPackage");
                });

            modelBuilder.Entity("TravelManagement.API.Models.Notification", b =>
                {
                    b.HasOne("TravelManagement.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelManagement.API.Models.PackageFacility", b =>
                {
                    b.HasOne("TravelManagement.API.Models.Facility", "Facility")
                        .WithMany("PackageFacilities")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelManagement.API.Models.TourPackage", "TourPackage")
                        .WithMany("PackageFacilities")
                        .HasForeignKey("TourPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facility");

                    b.Navigation("TourPackage");
                });

            modelBuilder.Entity("TravelManagement.API.Models.Payment", b =>
                {
                    b.HasOne("TravelManagement.API.Models.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("TravelManagement.API.Models.Refund", b =>
                {
                    b.HasOne("TravelManagement.API.Models.Booking", "Booking")
                        .WithOne("Refund")
                        .HasForeignKey("TravelManagement.API.Models.Refund", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("TravelManagement.API.Models.Review", b =>
                {
                    b.HasOne("TravelManagement.API.Models.Booking", "Booking")
                        .WithOne("Review")
                        .HasForeignKey("TravelManagement.API.Models.Review", "BookingId");

                    b.HasOne("TravelManagement.API.Models.Customer", "Customer")
                        .WithMany("Reviews")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelManagement.API.Models.Tour", "Tour")
                        .WithMany("Reviews")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Customer");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("TravelManagement.API.Models.Staff", b =>
                {
                    b.HasOne("TravelManagement.API.Models.User", "User")
                        .WithOne("Staff")
                        .HasForeignKey("TravelManagement.API.Models.Staff", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelManagement.API.Models.TourPackage", b =>
                {
                    b.HasOne("TravelManagement.API.Models.Tour", "Tour")
                        .WithMany("Packages")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("TravelManagement.API.Models.TourSchedule", b =>
                {
                    b.HasOne("TravelManagement.API.Models.Tour", "Tour")
                        .WithMany("Schedules")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelManagement.API.Models.TourPackage", "TourPackage")
                        .WithMany("Schedules")
                        .HasForeignKey("TourPackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tour");

                    b.Navigation("TourPackage");
                });

            modelBuilder.Entity("TravelManagement.API.Models.VehicleAllocation", b =>
                {
                    b.HasOne("TravelManagement.API.Models.Booking", "Booking")
                        .WithMany("VehicleAllocations")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TravelManagement.API.Models.Driver", "Driver")
                        .WithMany("Allocations")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TravelManagement.API.Models.Vehicle", "Vehicle")
                        .WithMany("Allocations")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Driver");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("TravelManagement.API.Models.Booking", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Refund");

                    b.Navigation("Review");

                    b.Navigation("VehicleAllocations");
                });

            modelBuilder.Entity("TravelManagement.API.Models.Customer", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("TravelManagement.API.Models.Driver", b =>
                {
                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("TravelManagement.API.Models.Facility", b =>
                {
                    b.Navigation("PackageFacilities");
                });

            modelBuilder.Entity("TravelManagement.API.Models.Tour", b =>
                {
                    b.Navigation("Packages");

                    b.Navigation("Reviews");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("TravelManagement.API.Models.TourPackage", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Itineraries");

                    b.Navigation("PackageFacilities");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("TravelManagement.API.Models.TourSchedule", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("TravelManagement.API.Models.User", b =>
                {
                    b.Navigation("Customer");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("TravelManagement.API.Models.Vehicle", b =>
                {
                    b.Navigation("Allocations");
                });
#pragma warning restore 612, 618
        }
    }
}
